name: voicebot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  forui: ^0.17.0
  forui_assets: ^0.17.1
  go_router: ^17.0.1
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  permission_handler: ^11.3.1
  mqtt_client: ^10.3.0
  pointycastle: ^3.9.1
  synchronized: ^3.3.0
  flutter_sound: ^9.2.13
  path_provider: ^2.1.3
  opus_flutter: ^3.0.3
  opus_dart: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  test: ^1.25.2

flutter:
  uses-material-design: true
